[codex]
src.webpage = "https://registry.npmjs.org/@openai/codex"
src.regex = "\"latest\":\"([^\"]+)\""
fetch.url = "https://registry.npmjs.org/@openai/codex/-/codex-$ver.tgz"

[claude-code]
src.webpage = "https://registry.npmjs.org/@anthropic-ai/claude-code"
src.regex = "\"latest\":\"([^\"]+)\""
fetch.url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-$ver.tgz"

[gemini-cli]
src.github = "google-gemini/gemini-cli"
src.from_pattern = "^v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/google-gemini/gemini-cli/releases/download/v$ver/gemini.js"
