# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  claude-code = {
    pname = "claude-code";
    version = "2.1.23";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.23.tgz";
      sha256 = "sha256-d5lDUN2Lyw6meXBFY3EiMt/7BNLVYX7xRnbPMjPpx7g=";
    };
  };
  codex = {
    pname = "codex";
    version = "0.92.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@openai/codex/-/codex-0.92.0.tgz";
      sha256 = "sha256-fwdRhO5K8qLWr/Yb1JT6g0fLsCGZS9kdIYQpiVfTtsY=";
    };
  };
  gemini-cli = {
    pname = "gemini-cli";
    version = "0.26.0";
    src = fetchurl {
      url = "https://github.com/google-gemini/gemini-cli/releases/download/v0.26.0/gemini.js";
      sha256 = "sha256-IOx+n39JGYmHp42ObLD30H2Lgpju6bDBQ7fHLP1oc60=";
    };
  };
}
