local map = vim.keymap.set

map("n", "<Esc>", "<cmd>nohlsearch<CR><Esc>", { desc = "Escape and Clear hlsearch" })

map("n", "<leader>w", "<cmd>write<CR>", { desc = "Write buffer" })
map("n", "<leader>q", "<cmd>quit<CR>", { desc = "Quit window" })
map({ "n", "i", "v" }, "<C-s>", "<cmd>write<CR><Esc>", { desc = "Save File" })

map("n", "<C-h>", "<C-w>h", { desc = "Go to Left Window" })
map("n", "<C-j>", "<C-w>j", { desc = "Go to Lower Window" })
map("n", "<C-k>", "<C-w>k", { desc = "Go to Upper Window" })
map("n", "<C-l>", "<C-w>l", { desc = "Go to Right Window" })

map("n", "<leader>ff", function()
  Snacks.picker.files({ hidden = true, ignored = false })
end, { desc = "Find Files" })
map("n", "<leader>fg", function()
  Snacks.picker.grep({ hidden = true, ignored = false })
end, { desc = "Live Grep" })
map("n", "<leader>fb", function()
  Snacks.picker.buffers()
end, { desc = "Find Buffers" })
map("n", "<leader>fo", function()
  Snacks.picker.recent()
end, { desc = "Recent Files" })
map("n", "<leader>fc", function()
  Snacks.picker.commands()
end, { desc = "Find Commands" })
map("n", "<leader>fh", function()
  Snacks.picker.help()
end, { desc = "Find Help" })

map("n", "-", function()
  Snacks.explorer()
end, { desc = "File Explorer" })
map("n", "<leader>e", function()
  Snacks.explorer()
end, { desc = "File Explorer" })

map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<CR>", { desc = "Diagnostics (Trouble)" })
map("n", "<leader>xq", "<cmd>Trouble qflist toggle<CR>", { desc = "Quickfix (Trouble)" })
map("n", "<leader>xt", "<cmd>TodoTrouble<CR>", { desc = "TODO list (Trouble)" })

map("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
map("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
map("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line Diagnostics" })

map("v", "<", "<gv", { desc = "Indent Left" })
map("v", ">", ">gv", { desc = "Indent Right" })

map("n", "<A-j>", "<cmd>move .+1<CR>==", { desc = "Move Down" })
map("n", "<A-k>", "<cmd>move .-2<CR>==", { desc = "Move Up" })
map("i", "<A-j>", "<Esc><cmd>move .+1<CR>==gi", { desc = "Move Down" })
map("i", "<A-k>", "<Esc><cmd>move .-2<CR>==gi", { desc = "Move Up" })
map("v", "<A-j>", ":move '>+1<CR>gv=gv", { desc = "Move Down" })
map("v", "<A-k>", ":move '<-2<CR>gv=gv", { desc = "Move Up" })

map("n", "<leader>gg", function()
  Snacks.lazygit()
end, { desc = "LazyGit" })
