name: "CI"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-25.05-darwin

      - name: Run Statix Check
        run: nix run github:nerdypepper/statix -- check .

      - name: Run Nix Flake Check
        run: nix flake check

      - name: Build darwin configuration (common)
        run: nix build .#darwinConfigurations.common.system

      - name: Build darwin configuration (commercial)  
        run: nix build .#darwinConfigurations.commercial.system

      - name: Build minimum configuration (common-minimum)
        run: nix build .#darwinConfigurations.common-minimum.system

      - name: Build full configuration (common-full)
        run: nix build .#darwinConfigurations.common-full.system