name: "CI"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-25.05-darwin

      - name: Run Statix Check
        run: nix run github:nerdypepper/statix -- check .#common

      - name: Run Nix Flake Check
        run: nix flake check

      - name: Build home-manager configuration for macOS
        run: nix build .#homeConfigurations."u1s-MacBook-Air".activationPackage
